#define __NR_exit 1
#define __NRargs_exit 1
#define __SYSCALL_for_exit  _SYSCALL1
#define __NR_fork 2
#define __NRargs_fork 0
#define __SYSCALL_for_fork  _SYSCALL0
#define __NR_read 3
#define __NRargs_read 3
#define __SYSCALL_for_read  _SYSCALL3
#define __NR_write 4
#define __NRargs_write 3
#define __SYSCALL_for_write  _SYSCALL3
#define __NR_open 5
#define __NRargs_open 3
#define __SYSCALL_for_open  _SYSCALL3
#define __NR_close 6
#define __NRargs_close 1
#define __SYSCALL_for_close  _SYSCALL1
#define __NR_wait4 7
#define __NRargs_wait4 4
#define __SYSCALL_for_wait4  _SYSCALL4
#define __NR_link 9
#define __NRargs_link 2
#define __SYSCALL_for_link  _SYSCALL2
#define __NR_unlink 10
#define __NRargs_unlink 1
#define __SYSCALL_for_unlink  _SYSCALL1
#define __NR_execve 11
#define __NRargs_execve 3
#define __SYSCALL_for_execve  _SYSCALL3
#define __NR_chdir 12
#define __NRargs_chdir 1
#define __SYSCALL_for_chdir  _SYSCALL1
#define __NR_mknod 14
#define __NRargs_mknod 3
#define __SYSCALL_for_mknod  _SYSCALL3
#define __NR_chmod 15
#define __NRargs_chmod 2
#define __SYSCALL_for_chmod  _SYSCALL2
#define __NR_chown 16
#define __NRargs_chown 3
#define __SYSCALL_for_chown  _SYSCALL3
#define __NR_brk 17
#define __NRargs_brk 1
#define __SYSCALL_for_brk  _SYSCALL1
#define __NR_stat 18
#define __NRargs_stat 2
#define __SYSCALL_for_stat  _SYSCALL2
#define __NR_lseek 19
#define __NRargs_lseek 3
#define __SYSCALL_for_lseek  _SYSCALL3
#define __NR_getpid 20
#define __NRargs_getpid 1
#define __SYSCALL_for_getpid  _SYSCALL1
#define __NR_mount 21
#define __NRargs_mount 5
#define __SYSCALL_for_mount  _SYSCALL5
#define __NR_umount 22
#define __NRargs_umount 1
#define __SYSCALL_for_umount  _SYSCALL1
#define __NR_setuid 23
#define __NRargs_setuid 1
#define __SYSCALL_for_setuid  _SYSCALL1
#define __NR_getuid 24
#define __NRargs_getuid 1
#define __SYSCALL_for_getuid  _SYSCALL1
#define __NR_fstat 28
#define __NRargs_fstat 2
#define __SYSCALL_for_fstat  _SYSCALL2
#define __NR_utime 30
#define __NRargs_utime 2
#define __SYSCALL_for_utime  _SYSCALL2
#define __NR_chroot 31
#define __NRargs_chroot 1
#define __SYSCALL_for_chroot  _SYSCALL1
#define __NR_vfork 32
#define __NRargs_vfork 0
#define __SYSCALL_for_vfork  _SYSCALL0
#define __NR_access 33
#define __NRargs_access 2
#define __SYSCALL_for_access  _SYSCALL2
#define __NR_sync 36
#define __NRargs_sync 0
#define __SYSCALL_for_sync  _SYSCALL0
#define __NR_kill 37
#define __NRargs_kill 2
#define __SYSCALL_for_kill  _SYSCALL2
#define __NR_rename 38
#define __NRargs_rename 2
#define __SYSCALL_for_rename  _SYSCALL2
#define __NR_mkdir 39
#define __NRargs_mkdir 2
#define __SYSCALL_for_mkdir  _SYSCALL2
#define __NR_rmdir 40
#define __NRargs_rmdir 1
#define __SYSCALL_for_rmdir  _SYSCALL1
#define __NR_dup 41
#define __NRargs_dup 1
#define __SYSCALL_for_dup  _SYSCALL1
#define __NR_pipe 42
#define __NRargs_pipe 1
#define __SYSCALL_for_pipe  _SYSCALL1
#define __NR_dup2 45
#define __NRargs_dup2 2
#define __SYSCALL_for_dup2  _SYSCALL2
#define __NR_setgid 46
#define __NRargs_setgid 1
#define __SYSCALL_for_setgid  _SYSCALL1
#define __NR_signal 48
#define __NRargs_signal 2
#define __SYSCALL_for_signal  _SYSCALL2
#define __NR_fcntl 50
#define __NRargs_fcntl 3
#define __SYSCALL_for_fcntl  _SYSCALL3
#define __NR_ioctl 54
#define __NRargs_ioctl 3
#define __SYSCALL_for_ioctl  _SYSCALL3
#define __NR_reboot 55
#define __NRargs_reboot 3
#define __SYSCALL_for_reboot  _SYSCALL3
#define __NR_lstat 57
#define __NRargs_lstat 2
#define __SYSCALL_for_lstat  _SYSCALL2
#define __NR_symlink 58
#define __NRargs_symlink 2
#define __SYSCALL_for_symlink  _SYSCALL2
#define __NR_readlink 59
#define __NRargs_readlink 3
#define __SYSCALL_for_readlink  _SYSCALL3
#define __NR_umask 60
#define __NRargs_umask 1
#define __SYSCALL_for_umask  _SYSCALL1
#define __NR_settimeofday 61
#define __NRargs_settimeofday 2
#define __SYSCALL_for_settimeofday  _SYSCALL2
#define __NR_gettimeofday 62
#define __NRargs_gettimeofday 2
#define __SYSCALL_for_gettimeofday  _SYSCALL2
#define __NR_select 63
#define __NRargs_select 5
#define __SYSCALL_for_select  _SYSCALL5
#define __NR_readdir 64
#define __NRargs_readdir 3
#define __SYSCALL_for_readdir  _SYSCALL3
#define __NR_fchown 66
#define __NRargs_fchown 3
#define __SYSCALL_for_fchown  _SYSCALL3
#define __NR_dlload 67
#define __NRargs_dlload 2
#define __SYSCALL_for_dlload  _SYSCALL2
#define __NR_setsid 68
#define __NRargs_setsid 0
#define __SYSCALL_for_setsid  _SYSCALL0
#define __NR_socket 69
#define __NRargs_socket 3
#define __SYSCALL_for_socket  _SYSCALL3
#define __NR_bind 70
#define __NRargs_bind 3
#define __SYSCALL_for_bind  _SYSCALL3
#define __NR_listen 71
#define __NRargs_listen 2
#define __SYSCALL_for_listen  _SYSCALL2
#define __NR_accept 72
#define __NRargs_accept 3
#define __SYSCALL_for_accept  _SYSCALL3
#define __NR_connect 73
#define __NRargs_connect 3
#define __SYSCALL_for_connect  _SYSCALL3
#define __NR_knlvsn 74
#define __NRargs_knlvsn 1
#define __SYSCALL_for_knlvsn  _SYSCALL1
